# Generated by Django 4.1 on 2023-03-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclepath",
            name="node_departure_time",
            field=models.IntegerField(blank=True, null=True, verbose_name="路径节点离开时间"),
        ),
    ]
